### ISSUE TITLE
Input with STARSolo?

### ISSUE THREAD

**Issue by cnk113** [SimoneTiberi/DifferentialRegulation#1]
Hello,

I was wondering if it was possible to use other spliced/unspliced/ambi quantification tools such as with STARSolo's method (which I believe is just wrapped around Velocyto)? Specifically what slots should be filled out?

**Comment by SimoneTiberi** [comment]
Hi @cnk113 ,
I just noticed this issue.

At present we only allow input from alevin-fry, but yes I plan to extend this to incorporate other types of inputs (such as alevin, kallisto bustools and STARSolo).
I am focusing on other aspects though, so it'll take some months.

Cheers,
Simone
